version: "3.8"

# All variables are set in the .env file

services:
  traefik:
    image: "traefik:v3.5"
    # Get environment variables from .env file to pass to Traefik
    env_file: .env.traefik

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
      - "traefik-logs:/var/log/traefik"
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"

      # --- Router for the Dashboard ---
      - "traefik.http.routers.dashboard.rule=Host(`traefik.trelvik.net`)"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"

      # --- SSO Middleware ---
      - "traefik.http.routers.dashboard.middlewares=sso-auth"
      - "traefik.http.middlewares.sso-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.sso-auth.forwardauth.authResponseHeaders=X-Forwarded-User"

  traefik-forward-auth:
    image: "thomseddon/traefik-forward-auth:2"
    # Get environment variables from .env file to pass to Traefik Forward Auth
    env_file: .env.traefik-forward-auth
    networks:
      - traefik-net
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      # Router for all auth traffic (including /_oauth callback)
      - "traefik.http.routers.forward-auth.rule=Host(`auth.trelvik.net`)"
      - "traefik.http.routers.forward-auth.entrypoints=https"
      - "traefik.http.routers.forward-auth.tls=true"
      - "traefik.http.routers.forward-auth.tls.certresolver=myresolver"

      # Map to the forward-auth container on port 4181
      - "traefik.http.services.forward-auth.loadbalancer.server.port=4181"

networks:
  traefik-net:
    # Create the network externally first using:
    # `docker network create --driver=overlay traefik-net`
    external: true

volumes:
  traefik-logs:
    name: traefik-logs